#!/bin/bash
#
# Copyright (C) 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $# -eq 0 -o "$1" = "-h" -o "$1" = "--help" ]; then
    echo "usage: $0 keyname input [output]"
    echo "  output defaults to \${input%.*}.signed.\${input##*.}"
    exit 1
fi

# Set up prog to be the path of this script, including following symlinks,
# and set up progdir to be the fully-qualified pathname of its directory.
prog="$0"
toolname=`basename "$prog"`
while [ -h "${prog}" ]; do
    newProg=`/bin/ls -ld "${prog}"`
    newProg=`expr "${newProg}" : ".* -> \(.*\)$"`
    if expr "x${newProg}" : 'x/' >/dev/null; then
        prog="${newProg}"
    else
        progdir=`dirname "${prog}"`
        prog="${progdir}/${newProg}"
    fi
done
oldwd=`pwd`
progdir=`dirname "${prog}"`
cd "${progdir}"
progdir=`pwd`
prog="${progdir}"/`basename "${prog}"`
cd "${oldwd}"

jarfile=signapk.jar
libdir="$progdir"
keysdir="$progdir/keys"

if [ ! -r "$libdir/$jarfile" ]; then
    # set signapk.jar location for the SDK case
    libdir="$libdir/lib"
fi


if [ ! -r "$libdir/$jarfile" ]; then
    # set signapk.jar location for the Android tree case
    libdir=`dirname "$progdir"`/framework
    # also include the library directory for any provider native libraries
    providerLibdir=`dirname "$progdir"`/lib64
fi

if [ ! -r "$libdir/$jarfile" ]; then
    echo `basename "$prog"`": can't find $jarfile"
    exit 1
fi

# By default, give signapk a max heap size of 1 gig. This can be overridden
# by using a "-J" option (see below).
defaultMx="-Xmx1024M"

# The following will extract any initial parameters of the form
# "-J<stuff>" from the command line and pass them to the Java
# invocation (instead of to signapk). This makes it possible for you to add
# a command-line parameter such as "-JXmx256M" in your scripts, for
# example. "java" (with no args) and "java -X" give a summary of
# available options.

javaOpts=""

while expr "x$1" : 'x-J' >/dev/null; do
    opt=`expr "x$1" : 'x-J\(.*\)'`
    javaOpts="${javaOpts} -${opt}"
    if expr "x${opt}" : "xXmx[0-9]" >/dev/null; then
        defaultMx="no"
    elif expr "x${opt}" : "xDjava.library.path=" >/dev/null; then
        defaultLibdir="no"
    fi
    shift
done

if [ "${defaultMx}" != "no" ]; then
    javaOpts="${javaOpts} ${defaultMx}"
fi

if [ "${defaultLibdir}" != "no" ] && [ -n $providerLibdir ]; then
    javaOpts="${javaOpts} -Djava.library.path=$providerLibdir"
fi

if [ "$OSTYPE" = "cygwin" ]; then
    # For Cygwin, convert the jarfile path into native Windows style.
    jarpath=`cygpath -w "$libdir/$jarfile"`
else
    jarpath="$libdir/$jarfile"
fi

args=""
if [ "$toolname" = "signrom" ]; then
    args="-w --disable-v2"
else
    args="-a 4"
fi

keyname="$1"
input="$2"
output="$3"
if [ -z "$output" ]; then
    outdir=`dirname "$input"`
    inputname=`basename "$input"`
    namewithoutsigned="${inputname%.*}"
    namewithoutsigned="${namewithoutsigned%.signed}"
    if [ "${inputname##*.}" != "signed" -a "${inputname##*.}" != "$inputname" ]; then
        namewithoutsigned="${namewithoutsigned}.${inputname##*.}"
    fi
    if [ "${namewithoutsigned##*.}" = "$namewithoutsigned" ]; then
        namewithoutsigned="${namewithoutsigned}.signed"
    else
        namewithoutsigned="${namewithoutsigned%.*}.signed.${namewithoutsigned##*.}"
    fi
    if [ "${inputname}" = "${namewithoutsigned}" ]; then
        namewithoutsigned="_${namewithoutsigned}"
    fi
    output="${outdir}/${namewithoutsigned}"
fi

echo "Signing $input with key $keyname, outputting to $output"

exec java $javaOpts --enable-native-access=ALL-UNNAMED -jar "$jarpath" $args "$keysdir/$keyname.x509.pem" "$keysdir/$keyname.pk8" "$input" "$output"
